#!/usr/bin/env Rscript

# Script Info: this just turns a fastq file into a fasta file in the DUMBEST way possible
# it preserves ALL sequence name stuff, and doesn't process the sequence at all. 
# by JLD, Oct 2017

suppressPackageStartupMessages(require(optparse))

# parse arguments
option_list <- list(
	make_option(c("-i", "--input"), action="store", default=NA, type='character',
		help="Input fastq file path."), 
	make_option(c("-o", "--output"), action="store", default=NA, type='character',
		help="Output fasta file path")
) 
opt = parse_args(OptionParser(option_list=option_list))

# function to read in fasta or fastq file as list
# NOTE: ONLY WORKS ON SEQUENTIAL FASTX FILES. 
# Hope you aren't still using interleaved files after like 2005
read.fastx <- function(file, type=c("fastq", "fasta")){
	# read in raw data
	lines <- scan(file, what="character", sep='\n')
	
	# check to make sure data are OK-ish
	nlines <- length(lines)
	if(type=="fastq" & nlines %% 4 > 0){
		stop("CRITICAL ERROR: number of lines in fastq file not divisible by 4.")
	}else if(type == "fasta" & nlines %% 2 > 0){
		stop("CRITICAL ERROR: number of lines in fasta file not divisible by 2")
	}

	# make indices for item types (1=header, 2=seq, 3="+", 4=qual)
	if(type=="fastq"){
		line_inds <- rep(1:4, nlines/4)
	}else if(type=="fasta"){
		line_inds <- rep(1:2, nlines/2)
	}

	# make names generic
	headers <- as.vector(sapply(X=lines[line_inds == 1], FUN=function(x) substring(x, 2) ) )

	# make output list object
	if(type=="fastq"){
		output <- mapply(FUN=c, lines[line_inds == 2], lines[line_inds == 4], SIMPLIFY=FALSE)
	}else if(type=="fasta"){
		output <- mapply(FUN=c, lines[line_inds == 2], SIMPLIFY=FALSE)
	}

	# add names to output list
	names(output) <- headers

	# all done
	return(output)

}

# function to wrout out a fasta or fastq file from a list as generated by read_fastx
write.fastx <- function(outfile, fastxlist, out=c("fastq", "fasta")){
	# decide how to make header
	if(out=="fastq"){
		headchar <- "@"
	}else if(out=="fasta"){
		headchar <- ">"
	}

	# write out file, line-by-line
	for(i in 1:length(fastxlist)){
		firstline <- i == 1
		header_i <- paste(headchar, names(fastxlist[i]), sep="")

		# write header, don't append if it's the first line
		write(header_i, file=outfile, append=firstline==FALSE)

		# write sequence
		write(fastxlist[[i]][1], file=outfile, append=TRUE)

		# if fastq, write + and qual
		if(out=="fastq"){
			write("+", file=outfile, append=TRUE)
			write(fastxlist[[i]][2], file=outfile, append=TRUE)
		}
	}
}

input_fastq <- read.fastx(file=opt$input, type="fastq")

write.fastx(outfile=opt$output, input_fastq, out="fasta")







